################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/debug.c \
/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/http_server_callbacks.c \
/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/main.c \
/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/stm32h7xx_it.c \
/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/system_stm32h7xx.c 

OBJS += \
./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/debug.o \
./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/http_server_callbacks.o \
./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/main.o \
./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/stm32h7xx_it.o \
./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/system_stm32h7xx.o 

C_DEPS += \
./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/debug.d \
./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/http_server_callbacks.d \
./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/main.d \
./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/stm32h7xx_it.d \
./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/system_stm32h7xx.d 


# Each subdirectory must supply rules for building sources it contributes
App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/debug.o: /home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/debug.c App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F407xx -c -I../Core/Inc -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/App/App/config" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/common" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/cyclone_boot" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/cyclone_crypto" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwbtn/src/include" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwbtn/src/include/lwbtn" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwprintf/src/include" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwprintf/src/include/lwprintf" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwprintf/src/include/system" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/stm32_log" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/ymodem" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/http_server_callbacks.o: /home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/http_server_callbacks.c App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F407xx -c -I../Core/Inc -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/App/App/config" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/common" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/cyclone_boot" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/cyclone_crypto" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwbtn/src/include" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwbtn/src/include/lwbtn" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwprintf/src/include" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwprintf/src/include/lwprintf" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwprintf/src/include/system" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/stm32_log" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/ymodem" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/main.o: /home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/main.c App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F407xx -c -I../Core/Inc -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/App/App/config" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/common" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/cyclone_boot" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/cyclone_crypto" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwbtn/src/include" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwbtn/src/include/lwbtn" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwprintf/src/include" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwprintf/src/include/lwprintf" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwprintf/src/include/system" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/stm32_log" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/ymodem" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/stm32h7xx_it.o: /home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/stm32h7xx_it.c App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F407xx -c -I../Core/Inc -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/App/App/config" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/common" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/cyclone_boot" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/cyclone_crypto" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwbtn/src/include" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwbtn/src/include/lwbtn" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwprintf/src/include" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwprintf/src/include/lwprintf" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwprintf/src/include/system" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/stm32_log" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/ymodem" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/system_stm32h7xx.o: /home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/system_stm32h7xx.c App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F407xx -c -I../Core/Inc -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/App/App/config" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/common" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/cyclone_boot" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/CycloneBOOT_Open_2_5_0/cyclone_crypto" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwbtn/src/include" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwbtn/src/include/lwbtn" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwprintf/src/include" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwprintf/src/include/lwprintf" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/lwprintf/src/include/system" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/stm32_log" -I"/home/tecna-smart-lab/GitHub/OTA_Consulting/Firmware/OTA_Package/Middlewares/ymodem" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-App-2f-Middlewares-2f-CycloneBOOT_Open_2_5_0-2f-demo-2f-st-2f-nucleo_h743zi2-2f-iap_single_bank-2f-http_server_demo-2f-src

clean-App-2f-Middlewares-2f-CycloneBOOT_Open_2_5_0-2f-demo-2f-st-2f-nucleo_h743zi2-2f-iap_single_bank-2f-http_server_demo-2f-src:
	-$(RM) ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/debug.cyclo ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/debug.d ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/debug.o ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/debug.su ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/http_server_callbacks.cyclo ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/http_server_callbacks.d ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/http_server_callbacks.o ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/http_server_callbacks.su ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/main.cyclo ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/main.d ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/main.o ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/main.su ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/stm32h7xx_it.cyclo ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/stm32h7xx_it.d ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/stm32h7xx_it.o ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/stm32h7xx_it.su ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/system_stm32h7xx.cyclo ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/system_stm32h7xx.d ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/system_stm32h7xx.o ./App/Middlewares/CycloneBOOT_Open_2_5_0/demo/st/nucleo_h743zi2/iap_single_bank/http_server_demo/src/system_stm32h7xx.su

.PHONY: clean-App-2f-Middlewares-2f-CycloneBOOT_Open_2_5_0-2f-demo-2f-st-2f-nucleo_h743zi2-2f-iap_single_bank-2f-http_server_demo-2f-src

